### ISSUE TITLE
what is q queries?

### ISSUE THREAD

**Issue by vitrinh282** [navjindervirdee/Advanced-Shortest-Paths-Algorithms#2]
int q = in.nextInt(); //number of queries.

	//get the queries
        for (int i = 0; i < q; i++) {
            int s, t;
            s = in.nextInt()-1;   //source vertex
            t = in.nextInt()-1;   //target vertex/
		
	    System.out.println(computeDistance(graph,reverseGraph,s,t,i));
	}
please help me explain input q

**Comment by navjindervirdee** [comment]
Q is the number of queries.

A query is to calculate shortest path between two nodes -- source and
target.
